from .enemy_base import Enemy
from .goblin import Goblin
from .huargo import Huargo
from .skeleton import Skeleton
from .bandido import Bandido
from .orc import Orc
from .espiritu_vengativo import EspirituVengativo
from .troll import Troll
from .gargola import Gargola
from .golem import GolemDePiedra
from .mage import Mago
from .nigromante import Nigromante
